server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: pkcs12
    key-store: keystore.p12
    key-store-password: 9979
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: https://k9b204.p.ssafy.io:8761/eureka
spring:
  application:
    name: gateway-service
  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: member-service
          uri: https://k9b204.p.ssafy.io:64417
          predicates:
            - Path=/api/member/**, /api/auth/**, /api/user/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: calling-service
          uri: https://k9b204.p.ssafy.io:64419
          predicates:
            - Path=/api/calling/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}

        - id: transfer-service
          uri: https://k9b204.p.ssafy.io:64415
          predicates:
            - Path=/api/transfer/**
          filters:
            - RewritePath=/api/(?<segment>.*), /$\{segment}